version: '3.7'

networks:
  network:
    name: net_1
    external: true

services:
    consul:
        image: consul:1.7
        hostname: consul
        ports:
            - "8500:8500"
            - "8501:8501"
        networks:
            - network
