version: '3.7'

networks:
    network:
        driver: bridge
        name: net_1

services:
    frontend:
        image: my-work
        ports:
            - '80:80'
            #- '443:443'
            - "3000:3000"
        volumes:
            - './nginx/conf:/etc/nginx/conf.d'
            - './nginx/certs:/etc/nginx/certs'
            - './nginx/vhost:/etc/nginx/vhost.d'
        networks:
            - network
