version: '3.7'

networks:
    network:
        driver: bridge
        name: net_1

services:
    keycloak:
        image: quay.io/keycloak/keycloak:17.0.0
        ports:
            - "8080:8080"
        networks:
            - network
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:
            - './data:/opt/keycloak/data/'
        command: start-dev
