version: '3.7'

networks:
  network:
    name: net_1
    external: true

services:
    elasticsearch:
        image: docker.io/elastic/elasticsearch:8.9.1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            discovery.type: "single-node"
            cluster.routing.allocation.disk.threshold_enabled: false
        networks:
            - network

    kibana:
        image: docker.io/elastic/kibana:8.9.1
        ports:
            - "5601:5601"
        networks:
            - network
        depends_on:
            - elasticsearch

    logstash:
        image: docker.io/elastic/logstash:8.9.1
        volumes:
            - source: './pipelines'
              target: /usr/share/logstash/pipeline
              type: bind
        ports:
            - "12201:12201/udp"
            - "5000:5000"
            - "9600:9600"
        networks:
            - network
        depends_on:
            - kibana
