version: '3.7'

networks:
    network:
        driver: bridge
        name: net_1

services:
    backend_2:
        image: quarkus/coursework-jvm
        ports:
            - "8082:8081"
        networks:
            - network
